'use client';
    import { useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent, type WheelEvent as ReactWheelEvent } from 'react';
    const APEX_RED = '#D80000';
    const EVENTS = [
    { slug: 'genesis', name: 'GENESIS', kind: 'Workshop · Gameathon', date: '2 days', poster: '/images/clubs/apex/events/genesis.jpg', video: '/videos/apex-genesis.mp4', body: 'A two-day Unity intensive. Industry mentors from Backstage Pass on day one — teams shipped full games from scratch on day two.' },
    { slug: 'vcc', name: 'VCC', kind: 'Tournament · Valorant', date: 'Wild Gaming Cafe', poster: '/images/clubs/apex/events/vcc.jpg', video: '/videos/apex-vcc.mp4', body: "MLRIT's first Valorant Campus Championship — hosted at Wild Gaming Cafe. Out of the tournament came the MLRIT Valorant roster." },
    { slug: 'interdept', name: 'Interdepartmental Esports', kind: 'Championship · BGMI + Valorant', date: '180+ players', poster: '/images/clubs/apex/events/interdept.jpg', video: '/videos/apex-interdept.mp4', body: 'The first-ever Interdepartmental Esports Championship — 180+ gamers, 17 departments, guests from Arundathi Institute of Medical Sciences.' },
    { slug: 'lan', name: 'LAN Nights', kind: 'Community · Casual', date: 'Recurring', poster: '/images/clubs/apex/gallery/1.jpg', video: '/videos/apex-lan.mp4', body: 'Regular LAN nights open to the full campus — casual play, new friendships, and the electric energy of side-by-side gaming.' },
    ] as const;
    type GalleryItem = { event: typeof EVENTS[number]; type: 'image' | 'video' };
    function EventMedia({ item }: { item: GalleryItem }) {
    const label = item.type === 'image' ? 'poster' : 'video';
    return (<figure className="group relative flex h-[62vw] max-h-[470px] min-h-[290px] w-[78vw] flex-shrink-0 flex-col overflow-hidden rounded-[2px] border border-white/10 bg-[#111] md:h-[30vw] md:w-[calc((100%-3rem)/4)] md:min-h-0"><div className="relative min-h-0 flex-1 overflow-hidden">{item.type === 'image' ? <img src={item.event.poster} alt={item.event.name + ' APEX event poster'} className="absolute inset-0 h-full w-full object-cover transition-transform duration-700 group-hover:scale-[1.04]" draggable={false} /> : <video src={item.event.video} poster={item.event.poster} muted loop playsInline preload="none" controls className="absolute inset-0 h-full w-full object-cover" aria-label={item.event.name + ' APEX event video'} />}<div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-black/80 via-black/10 to-transparent" /></div><figcaption className="flex items-center justify-between gap-3 px-3 py-3 text-white"><span className="font-mono text-[0.56rem] font-bold uppercase tracking-[0.18em] text-white/75">{item.event.name}</span><span className="font-mono text-[0.52rem] uppercase tracking-[0.18em]" style={{ color: APEX_RED }}>{label}</span></figcaption></figure>);
    }
    export default function ApexEventsGallery() {
    const railRef = useRef<HTMLDivElement>(null);
    const snapTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
    const drag = useRef({ active: false, startX: 0, startScroll: 0, lastX: 0, lastTime: 0, velocity: 0 });
    const [dragging, setDragging] = useState(false);
    const [progress, setProgress] = useState(0);
    const items = useMemo<GalleryItem[]>(() => EVENTS.flatMap(event => [{ event, type: 'image' }, { event, type: 'video' }]), []);
    const step = () => { const first = railRef.current?.firstElementChild as HTMLElement | null; return first ? first.getBoundingClientRect().width + 16 : 0; };
    const snap = () => { const rail = railRef.current; const cardStep = step(); if (!rail || !cardStep) return; rail.scrollTo({ left: Math.round(rail.scrollLeft / cardStep) * cardStep, behavior: 'smooth' }); };
    const handleDown = (event: ReactPointerEvent<HTMLDivElement>) => { const rail = railRef.current; if (!rail) return; drag.current = { active: true, startX: event.clientX, startScroll: rail.scrollLeft, lastX: event.clientX, lastTime: performance.now(), velocity: 0 }; rail.setPointerCapture(event.pointerId); setDragging(true); };
    const handleMove = (event: ReactPointerEvent<HTMLDivElement>) => { const rail = railRef.current; if (!rail || !drag.current.active) return; const now = performance.now(); const deltaX = event.clientX - drag.current.lastX; const deltaTime = Math.max(8, now - drag.current.lastTime); rail.scrollLeft = drag.current.startScroll - (event.clientX - drag.current.startX); drag.current.velocity = -(deltaX / deltaTime) * 16; drag.current.lastX = event.clientX; drag.current.lastTime = now; };
    const release = () => { const rail = railRef.current; if (!rail || !drag.current.active) return; drag.current.active = false; setDragging(false); let velocity = Math.max(-28, Math.min(28, drag.current.velocity)); const momentum = () => { const currentRail = railRef.current; if (!currentRail) return; velocity *= 0.92; currentRail.scrollLeft += velocity; if (Math.abs(velocity) > 0.25) requestAnimationFrame(momentum); else snap(); }; requestAnimationFrame(momentum); };
    const handleWheel = (event: ReactWheelEvent<HTMLDivElement>) => { const rail = railRef.current; if (!rail) return; if (Math.abs(event.deltaY) > Math.abs(event.deltaX)) event.preventDefault(); rail.scrollLeft += Math.abs(event.deltaY) > Math.abs(event.deltaX) ? event.deltaY : event.deltaX; if (snapTimer.current) clearTimeout(snapTimer.current); snapTimer.current = setTimeout(snap, 220); };
    useEffect(() => () => { if (snapTimer.current) clearTimeout(snapTimer.current); }, []);
    return (<section className="relative z-10 overflow-hidden py-20 md:py-28" aria-label="APEX events"><div className="mx-auto max-w-[1100px] px-6 md:px-10 lg:px-16"><div className="mb-4 flex items-center gap-3"><span aria-hidden className="h-px w-6" style={{ backgroundColor: APEX_RED }} /><span className="font-mono text-[0.68rem] font-bold uppercase tracking-[0.3em]" style={{ color: APEX_RED }}>Events</span></div><h2 className="mb-2 font-sans text-[clamp(1.8rem,3.2vw,2.8rem)] font-black leading-[1.02] text-white">The record.</h2><p className="mb-7 text-[0.88rem] text-white/35">Drag through — poster and video for each event.</p><div ref={railRef} className={dragging ? 'flex cursor-grabbing select-none gap-4 overflow-x-auto pb-4 snap-x snap-mandatory' : 'flex cursor-grab gap-4 overflow-x-auto pb-4 snap-x snap-mandatory'} style={{ scrollbarWidth: 'none', touchAction: 'pan-y' }} onPointerDown={handleDown} onPointerMove={handleMove} onPointerUp={release} onPointerCancel={release} onWheel={handleWheel} onScroll={(event) => { const el = event.currentTarget; setProgress(el.scrollWidth <= el.clientWidth ? 1 : el.scrollLeft / (el.scrollWidth - el.clientWidth)); }} role="region" aria-label="APEX event gallery, draggable" tabIndex={0}>{items.map((item) => <EventMedia item={item} key={item.event.slug + '-' + item.type} />)}</div><div className="mt-5 flex items-center gap-3" aria-label="Gallery progress" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(progress * 100)}><div className="h-px flex-1 bg-white/10"><div className="h-px bg-[#D80000] transition-[width] duration-150" style={{ width: String(Math.max(12, progress * 100)) + '%' }} /></div><span className="font-mono text-[0.56rem] uppercase tracking-[0.2em] text-white/30">{Math.round(progress * 100)}%</span></div></div></section>);
    }
    